fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.13.1"
    snmp: "https://github.com/razorsedge/puppet-snmp.git"
 
# default module layout

  symlinks:
    beng_nrpe: "#{source_dir}"
